### ISSUE TITLE
Alpine docker build error

### ISSUE THREAD

**Issue by AskAlexSharov** [RoaringBitmap/gocroaring#22]
Dockerfile:
```
FROM golang:1.15-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git

WORKDIR /app

ADD . .
RUN go build .
```

Error:

```
# github.com/RoaringBitmap/gocroaring
cgo-gcc-prolog: In function '_cgo_e935942c1c5f_Cmacro_stdout':
cgo-gcc-prolog:903:9: error: assignment of read-only variable '_cgo_r'
cgo-gcc-prolog:906:12: error: assignment of read-only member 'r'
```

Minimal reproducable project:  
git clone https://github.com/RoaringBitmap/gocroaring
cd goroaring/proj
docker build .

Code:
https://github.com/RoaringBitmap/gocroaring/compare/master...AskAlexSharov:docker_test?expand=1

**Comment by lemire** [comment]
We have CI tests with 1.15:
https://github.com/RoaringBitmap/gocroaring/blob/master/.github/workflows/test.yml


You can verify that everything is fine with the regular golang images...

```
$ docker run -it  -v $(pwd):$(pwd):Z  -w $(pwd)   golang:1.15.2 bash
root@00c174227353:/Users/lemire/CVS/github/gocroaring# go test
CRoaring 0.2.65
Alloc = 4 MiB	TotalAlloc = 41 MiB	Sys = 70 MiB	NumGC = 11
Alloc = 2 MiB	TotalAlloc = 80 MiB	Sys = 70 MiB	NumGC = 23
Alloc = 3 MiB	TotalAlloc = 120 MiB	Sys = 70 MiB	NumGC = 34
Alloc = 2 MiB	TotalAlloc = 159 MiB	Sys = 70 MiB	NumGC = 46
...
```

I understand that you want to build your own image from the minimalist alpine builds. That is a fine and interesting project, but the fact that you are encountering issues is not indicative of a bug in gocroaring.

If you believe that there is a bug in gocroaring, please open an issue where you explain your rationale.

**Comment by AskAlexSharov** [comment]
I got docker image from here: https://hub.docker.com/_/golang

Just it's not clear for me - is "alpine" in the list of "supported" OS or not? 

There is no real rationale, just alpine is popular in Docker world.

**Comment by willglynn** [comment]
🤔 Is this a `cgo` + `musl` issue?

**Comment by lemire** [comment]
See this latest commit which may solve your issue... https://github.com/RoaringBitmap/gocroaring/commit/279326f43077757cac131d0008f10e9bfe4debda

> Just it's not clear for me - is "alpine" in the list of "supported" OS or not?

The continuous integration platforms are what is supported. We cannot support what does not get tested systematically. If you wish to see alpine supported, then please provide a pull request that adds alpine continuous integration tests.

This is not just true of this project here, it is a universal principle. 

So to answer specifically your question: we do not support alpine. We can support alpine if someone will contribute the scripts for us to run CI tests under alpine.


> Is this a cgo + musl issue?

Quite possibly.

**Comment by lemire** [comment]
@AskAlexSharov In other words, if you'd like that this project supports Alpine, then I invite you to contribute the corresponding CI scripts. Same remark regarding any other platform you'd like to see supported.

**Comment by AskAlexSharov** [comment]
Thank, guys. Must be doable for me. I will come back with PR soon.
